models:
  - name: resnet-18

    launchers:
      - framework: onnx_runtime
        model: public/resnet-18/caffe2/resnet-v1-18.onnx
        adapter: classification
        inputs:
          - name: data
            type: INPUT
            shape: 1,3,224,224

    datasets:
      - name: imagenet_1000_classes
        reader: pillow_imread

        # In order to be used by model, images must be:
        # 1) Resized to 256x256 with bilinear interpolation
        # 2) Cropped central part 224x224
        # 3) Normalized by 255
        # 4) Normalized by (0.229, 0.224, 0.225) with mean values (0.485, 0.456, 0.406)
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
            use_pillow: true
            interpolation: BILINEAR

          - type: crop
            size: 224
            use_pillow: true

          - type: normalization
            std: 255

          - type: normalization
            mean: (0.485, 0.456, 0.406)
            std: (0.229, 0.224, 0.225)

            # Reference metric from PyTorch (pytorch v1.3.1, torchvision v0.4.2) top-1 69.76% top-5 89.08%

  - name: resnet-18

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/resnet-18/caffe2/FP32/resnet-v1-18.xml
        weights: public/resnet-18/caffe2/FP32/resnet-v1-18.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        reader: pillow_imread

        # Image channels must be swapped, because "pillow_imread" reads in RGB, but converted model expect BGR
        preprocessing:
          - type: bgr_to_rgb

          - type: resize
            size: 256
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BILINEAR
          - type: crop
            size: 224
            use_pillow: True

global_definitions: ../dataset_definitions.yml
